---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prod-eks
  region: ap-southeast-1
  version: '1.22'

nodeGroups:
  - name: node-group-1
    instanceType: m5.large
    minSize: 2
    maxSize: 3
    desiredCapacity: 2
    privateNetworking: true
    availabilityZones: ["ap-southeast-1a", "ap-southeast-1b", "ap-southeast-1c"]
#    labels: { type: prod }
iam:
  withOIDC: true




